"""add ai_colors and ai_scene_type

Revision ID: 70f8fd02bc8c
Revises: adb9a2bb8140
Create Date: 2026-03-17 17:02:13.166908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f8fd02bc8c'
down_revision: Union[str, Sequence[str], None] = 'adb9a2bb8140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_colors', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_scene_type', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('ai_scene_type')
        batch_op.drop_column('ai_colors')

    # ### end Alembic commands ###
