"""add multilingual ai description fields

Revision ID: adb9a2bb8140
Revises: 56983aeb697d
Create Date: 2026-03-17 16:50:55.790015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb9a2bb8140'
down_revision: Union[str, Sequence[str], None] = '56983aeb697d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_description_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_tags_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_description_fi', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_tags_fi', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('ai_tags_fi')
        batch_op.drop_column('ai_description_fi')
        batch_op.drop_column('ai_tags_en')
        batch_op.drop_column('ai_description_en')

    # ### end Alembic commands ###
