"""add rejected_at, kept_at, tagged_at timestamps

Revision ID: b1efd023d752
Revises: 29c29d0f7195
Create Date: 2026-04-04 08:49:06.810316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1efd023d752'
down_revision: Union[str, Sequence[str], None] = '29c29d0f7195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('kept_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tagged_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('tagged_at')
        batch_op.drop_column('kept_at')
        batch_op.drop_column('rejected_at')

    # ### end Alembic commands ###
