"""add file_hash column to images

Revision ID: f3624bab8359
Revises: 7937d3063d77
Create Date: 2026-04-16 05:17:42.201272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3624bab8359'
down_revision: Union[str, Sequence[str], None] = '7937d3063d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_hash', sa.Text(), nullable=True))
        batch_op.create_index('ix_images_file_hash', ['file_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index('ix_images_file_hash')
        batch_op.drop_column('file_hash')

    # ### end Alembic commands ###
